apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-cronjob-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-cronjob-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "list", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-cronjob-rolebinding
subjects:
- kind: ServiceAccount
  name: spark-cronjob-sa
roleRef:
  kind: Role
  name: spark-cronjob-role
  apiGroup: rbac.authorization.k8s.io