---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name:  {{ include "common.names.fullname" . }}-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name:  {{ include "common.names.fullname" . }}-rolebinding
subjects:
- kind: ServiceAccount
  name:  {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name:  {{ include "common.names.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
