#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Default values for superset.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: sunbird
nameOverride: superset
fullnameOverride: superset

replicaCount: 1

image:
  repository: sunbirded.azurecr.io/superset
  tag: release-7.0.0
  pullPolicy: Always

service:
  type: NodePort
  port: 8088

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Extra environment variables that will be passed into the superset container
extraEnv: {}
  # SUPERSET_ENV: production
  # SUPERSET_LOAD_EXAMPLES: yes

# Default credentials
credentials:
  adminUser: admin
  adminPassword: admin
  adminEmail: admin@example.com
  reviewerUser: report_reviewer
  reviewerPassword: reviewer
  reviewerEmail: report_reviewer@example.com
  creatorUser: report_creator
  creatorPassword: creator
  creatorEmail: report_creator@example.com

postgresql: &postgresql
  enabled: true
  host: postgresql
  postgresqlUsername: postgres
  postgresqlPassword: postgres

global:
  postgresql: *postgresql
  adminutil_learner_api_auth_key: ""



report_service_url: "http://report-service:3030"
analytics_api_service_url: "http://analytics-service:9000"

