apiVersion: v2
appVersion: 1.0.0
description: A Helm chart for Neo4j
name: neo4j
version: 0.1.0
dependencies:
  - name: common
    repository: https://nimbushubin.github.io/helmcharts
    version: 0.1.0