nameOverride: ""
fullnameOverride: ""

image:
  repository: sunbirded.azurecr.io/kong-scripts
  tag: "0.1.8"
  pullPolicy: IfNotPresent
  pullSecrets: []

kong_admin_url: kong
kong_admin_port: 8001

statsd_pulgin:
  name: statsd
  config.host: "statsd-service"
  config.port: "9125"
  config.metrics:
  - name: request_count
    sample_rate: 1
    stat_type: counter
  - name: latency
    stat_type: timer
  - name: request_size
    stat_type: timer
  - name: status_count
    sample_rate: 1
    stat_type: counter
  - name: response_size
    stat_type: timer
  - consumer_identifier: username
    name: unique_users
    stat_type: set
  - consumer_identifier: username
    name: request_per_user
    sample_rate: 1
    stat_type: counter
  - name: upstream_latency
    stat_type: timer
  - name: kong_latency
    stat_type: timer
  - consumer_identifier: username
    name: status_count_per_user
    sample_rate: 1
    stat_type: counter

# Default Rate limits
small_rate_limit_per_hour: 100
medium_rate_limit_per_hour: 5000
x_medium_rate_limit_per_hour: 5000
large_rate_limit_per_hour: 10000
x2_large_rate_limit_per_hour: 15000
x_large_rate_limit_per_hour: 30000

# Default max request size in MB
small_request_size_limit: 1
medium_request_size_limit: 10
large_request_size_limit: 100

premium_consumer_small_rate_limit_per_hour: 1000
premium_consumer_medium_rate_limit_per_hour: 10000
premium_consumer_large_rate_limit_per_hour: 100000

# External URL's
freshDesk_url: "http://dummy.freshDesk.url"

# Default service prefixes
learner_private_route_prefix: /private
private_content_prefix: /private/content
device_prefix: /v3/device
content_prefix: /content
tickets_prefix: /tickets
course_service_prefix: /course
itemset_prefix: /itemset
user_service_prefix: /user
data_service_prefix: /data
notes_service_prefix: /notes
org_service_prefix: /org
echo_service_prefix: /echo
composite_service_prefix: /composite
api_manager_perfix: /api-manager
meta_service_prefix: /meta
announcement_service_prefix: /announcement
dialcode_service_prefix: /dialcode
channel_service_prefix: /channel
framework_service_prefix: /framework
badge_service_prefix: /badging
plugin_service_prefix: /plugins
config_service_prefix: /config
textbook_service_prefix: /textbook
lock_service_prefix: /lock
otp_service_prefix: /otp
sso_service_prefix: /sso
cert_service_prefix: /cert
cert_registry_service_prefix: /certreg
desktop_app_prefix: /desktop
license_api_prefix: /license
report_service_prefix: /data/v1/report-service
analytics_report_service_prefix: /report/jobs
group_service_prefix: /group
auth_service_prefix: /auth
object_category_prefix: /object/category
object_category_definition_prefix: /object/category/definition
dataset_service_prefix: /dataset
asset_prefix: /asset
collection_prefix: /collection
discussions_prefix: /discussion
question_prefix: /question
questionset_prefix: /questionset
integration_app_prefix: /app
users_service_prefix: /users
solutions_service_prefix: /solutions
entities_service_prefix: /entities
cloud_service_prefix: /cloud-services
userProjects_service_prefix: /userProjects
reports_service_prefix: /reports
project_service_prefix: /project
observations_service_prefix: /observations
observationSubmissions_service_prefix: /observationSubmissions
surveys_service_prefix: /surveys
surveySubmissions_service_prefix: /surveySubmissions
user_extension_prefix: /user-extension
uci_admin_prefix: /uci
notification_service_prefix: /notification
registry_service_prefix: /rc
assessment_prefix: /assessment
programs_service_prefix: /programs
resource_prefix: /resource
learning_service_prefix: /learning

# Service URLs
knowledge_mw_service_url: "http://knowledge-mw-service:5000"
userorg_service_url: "http://userorg-service:9000"
dial_service_url: "http://dial-service:9000"
learning_service_url: "http://learning:8080/learning-service"
telemetry_service_url: "http://telemetry-service:9001"
player_service_url: "http://player:3000"
echo_service_url: "http://echo:9595"
am_util_url: "http://adminutil:4000"
config_service_url: "http://config-service:8080"
lms_service_url: "http://lms-service:9000"
cert_service_url: "http://cert-service:9000"
cert_registry_service_url: "http://cert-registry-service:9000"
content_service_url: "http://content-service:9000"
report_service_url: "http://report-service:3030"
group_service_url: "http://groups-service:9000"
analytics_api_service_url: "http://analytics-service:9000"
taxonomy_service_url: "http://taxonomy-service:9000"
discussions_mw_service_url: "http://discussionmw-service:3002/discussion"
assessment_service_url: "http://assessment-service:9000"
ml_reports_service_url: "http://ml-reports-service:3000"
ml_survey_service_url: "http://ml-survey-service:3000"
ml_project_service_url: "http://ml-projects-service:3000"
ml_core_service_url: "http://ml-core-service:3000"
uci_inbound_service_url: "http://inbound-service:8085"
uci_transformer_service_url: "http://trasnformer-service:9091"
uci_gql_service_url: "http://gql-service:8080"
uci_registry_service_url: "http://fusionauth-service:9011"
uci_admin_service_url: "http://uci-service:9999"
notification_service_url: "http://notification-service:9000"
registry_service_url: "http://registry-service:8081"

provisioningAnnotations:
  "helm.sh/hook": post-install,post-upgrade

configmap:
  enabled: true
  mountPath: /config
