---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.fullname" . }}
  annotations:
    {{- .Values.provisioningAnnotations | toYaml | nindent 4 }}
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-kong
        image: busybox
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/sh", "-c"]
        args:
        - "timeout 300 sh -c 'until nc -z kong 8000; do echo waiting for kong; sleep 10; done'"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - /bin/sh
          - -c
          args:
            - python /kong_yaml_to_json.py && python /kong_consumers.py /tmp/kong-consumers.json --kong-admin-api-url=http://{{    .Values.kong_admin_url }}:{{ .Values.kong_admin_port }}
          volumeMounts:
          {{- if .Values.configmap.enabled }}
          - name: config
            mountPath: {{ .Values.configmap.mountPath }}
          {{- end }}
      volumes:
      {{- if .Values.configmap.enabled }}
      - name: config
        configMap:
          name: {{ include "common.names.fullname" . }}
      {{- end }}
      restartPolicy: Never
  backoffLimit: 30
