{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
{{ include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
{{ include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
{{- $currentScope := .}}
{{- range $path, $_ := .Files.Glob "configs/**" }}
  {{- if ne $path "configs/env.yaml" }}
    {{base $path | nindent 2}}: |-
      {{- with $currentScope}}
      {{- $var := .Files.Get $path }}
      {{- include "common.tplvalues.render" (dict "value" $var "context" $) | nindent 4 -}}
      {{- end }}
  {{- end }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-env
  labels:
{{ include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
{{ include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
  {{- $var := .Files.Get "configs/env.yaml" }}
  {{- include "common.tplvalues.render" (dict "value" $var "context" $) | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: access-private-keys
data:
{{- range $key, $value := .Values.global.access_v1_private_keys }}
  {{ $key }}: |-
{{- $value | trim | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mobile-devicev2-private-keys
data:
{{- range $key, $value := .Values.global.mobile_devicev2_private_keys }}
  {{ $key }}: |+
{{- $value | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: desktop-devicev2-private-keys
data:
{{- range $key, $value := .Values.global.desktop_devicev2_private_keys }}
  {{ $key }}: |+
{{- $value | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-anonymous-private-keys
data:
{{- range $key, $value := .Values.global.portal_anonymous_private_keys }}
  {{ $key }}: |+
{{- $value | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-loggedin-private-keys
data:
{{- range $key, $value := .Values.global.portal_loggedin_private_keys }}
  {{ $key }}: |+
{{- $value | nindent 4 }}
{{- end }}
