apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: telemetry
version: 0.1.0
dependencies:
- name: common
  repository: https://nimbushubin.github.io/helmcharts
  version: 0.1.0