{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  telemetry_kafka_broker_list: {{ quote (printf "%s:%s" .Values.global.kafka.host (toString .Values.global.kafka.port)) | nindent 4 }}
{{- range $key, $value := .Values.sunbird_telemetry_service }}
  {{ $key }}: {{ quote $value | nindent 4 }}
{{- end }}
{{- end }}