apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-service
  labels:
    app: {{ include "common.names.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
  {{- end }}
  selector:
    app: {{ include "common.names.name" . }}
